-- 01
SELECT *
FROM heg_personne
WHERE per_clu_no = (SELECT per_clu_no FROM heg_personne WHERE LOWER(per_nom) = 'dorsa' OR LOWER(per_prenom) = 'dorsa');

-- 02
SELECT clu_nom || ' : ' || clu_email AS "Mail"
FROM heg_club
WHERE LOWER(clu_email) LIKE '%@heg.ch'
UNION
SELECT per_prenom || ' ' || per_nom || ' : ' ||per_email AS "Mail"
FROM heg_personne
WHERE LOWER(per_email) LIKE '%@heg.ch';

-- 03
SELECT clu_nom                                                               AS "Club",
       (SELECT COUNT(per_no) FROM heg_personne WHERE per_clu_no = clu_no)    AS "Nombre de membres",
       (SELECT COUNT(com_no) FROM heg_competition WHERE com_clu_no = clu_no) AS "Nombre de compétitions organisées"
FROM heg_club
GROUP BY clu_no, clu_nom;

-- 04
CREATE TABLE heg_federation (
    fed_no  INT GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT pk_fed_no PRIMARY KEY,
    fed_nom VARCHAR(50) NOT NULL
);

ALTER TABLE heg_club
    ADD clu_fed_no INT
        CONSTRAINT fk_clu_fed_no REFERENCES heg_federation (fed_no);

INSERT INTO heg_federation (fed_nom)
VALUES ('Swiss Athletics');
INSERT INTO heg_federation (fed_nom)
VALUES ('ASF (Association Suisse de Football)');
UPDATE heg_club
SET clu_fed_no = (SELECT fed_no FROM heg_federation WHERE fed_nom = 'Swiss Athletics')
WHERE clu_nom IN ('HEG-Running', 'Traînes-Savates BDD');
UPDATE heg_club
SET clu_fed_no = (SELECT fed_no FROM heg_federation WHERE fed_nom = 'ASF (Association Suisse de Football)')
WHERE clu_nom IN ('Football Club 62-31');
COMMIT;

SELECT clu_no AS "No", clu_nom AS "Club", fed_nom AS "Fédération"
FROM heg_club
    LEFT JOIN heg_federation ON clu_fed_no = fed_no;

-- 05 Insérer le nouveau club « HEG-Footing », affilié également à « Swiss Athletics », ayant comme président « Alain Proviste ». L’email du club est le même que celui de son président (la ville également).
INSERT INTO heg_club (clu_no, clu_nom, clu_per_no, clu_email, clu_ville, clu_fed_no)
VALUES ((SELECT MAX(clu_no) + 1 FROM heg_club), 'HEG-Footing',
        (SELECT per_no FROM heg_personne WHERE per_nom = 'Proviste' AND per_prenom = 'Alain'),
        (SELECT per_email FROM heg_personne WHERE per_nom = 'Proviste' AND per_prenom = 'Alain'),
        (SELECT per_ville FROM heg_personne WHERE per_nom = 'Proviste' AND per_prenom = 'Alain'),
        (SELECT fed_no FROM heg_federation WHERE fed_nom = 'Swiss Athletics'));
COMMIT;